# Generated by Django 3.2.7 on 2025-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
